### ISSUE TITLE
Sound API?

### ISSUE THREAD

**Issue by Elusivehawk** [Elusivehawk/CaelumEngine#5]
Now, this one will be tricky since Android, correct me if I'm wrong, lacks OpenAL support.

However, I'm just gonna open this up for future discussion.

**Comment by sriharshachilakapati** [comment]
OpenAL is available for android, with some hacks. I have found this article for you: http://pielot.org/2010/12/openal-on-android/

**Comment by Elusivehawk** [comment]
Actually @sriharshachilakapati, since Android support's gone, sound support will be added without hesitation; I just need to get the API right.

**Comment by sriharshachilakapati** [comment]
I think I missed that, good luck with your engine.

**Comment by Elusivehawk** [comment]
Also, closing down.
